# Generated by Django 6.0 on 2026-01-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="stripe_link",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_amount",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
    ]
