# Generated by Django 6.0 on 2026-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_stripe_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличными"), ("credit_card", "Перевод на счет"), ("stripe", "Stripe")],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
