# Generated by Django 6.0 on 2026-01-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="stripe_link",
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name="Ссылка на оплату"),
        ),
    ]
