# Generated by Django 5.2.10 on 2026-02-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_stripe_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Сумма оплаты"),
        ),
    ]
