# Generated by Django 5.2.10 on 2026-02-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(verbose_name="Дата оплаты"),
        ),
    ]
