# Generated by Django 6.0 on 2025-12-10 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название курса")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="course_preview/", verbose_name="Превью курса"),
                ),
                ("description", models.TextField(blank=True, max_length=200, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название урока")),
                ("description", models.TextField(blank=True, max_length=200, null=True, verbose_name="Описание")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="lesson_preview/", verbose_name="Превью урока"),
                ),
                ("video_link", models.URLField(verbose_name="Видео")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="lms.course"
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
